### ISSUE TITLE
Allow plugin permissions without closing confirmation box

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-plugin-beta#73]
Currently if you request a plugin installation, you get one confirmation to request installation, and a second for its permissions.

We could improve performance a bit by preventing this momentary window-close, and reuse the window we've already initialized to make both requests.

**Comment by rekmarks** [comment]
For whenever we decide to fix this, the popup closes due to `_closePopup` being called in `approvePermissionsRequest` or `rejectPermissionsRequest` in the permissions controller. `_closePopup` is called if the permission controller's `pendingApprovals.length === 0`.

To prevent the popup from being closed, we have to make the permissions controller wait for additional permissions requests (if any) before proceeding. I think we should do this by detecting plugin permissions among the approved permissions and then waiting for their installation to complete. This is only applicable for `wallet_enable` requests, as `wallet_installPlugins` only requests permissions for plugins, and _the popup already stays open for multiple simultaneous plugin installations._

**Comment by rekmarks** [comment]
Tracked elsewhere.
